# Generated by Django 4.0.4 on 2022-05-30 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField()),
                ('horario_salida', models.TimeField(null=True)),
                ('horario_llegada', models.TimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Buses',
                'db_table': 'api_app_buses',
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Choferes',
                'db_table': 'api_app_choferes',
            },
        ),
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Trayectos',
                'db_table': 'api_app_trayectos',
            },
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('asiento', models.IntegerField(null=True, unique=True)),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.bus')),
            ],
            options={
                'verbose_name_plural': 'Pasajeros',
                'db_table': 'api_app_pasajeros',
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='chofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.chofer'),
        ),
        migrations.AddField(
            model_name='bus',
            name='trayecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.trayecto'),
        ),
    ]
