# Generated by Django 4.0.4 on 2022-05-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='capacidad',
        ),
    ]
